### ISSUE TITLE
Doesn't not take scope values

### ISSUE THREAD

**Issue by tedoladele** [codekraft-studio/angular-typed#1]
< typed>Hi, my name is {{ted}}</typed

The above does not work. Am i doing something wrong?

**Comment by codekraft-studio** [comment]
Sorry for the late response, this code:

> < typed>Hi, my name is {{ted}}</typed

can't be done since the scope variables may vary during the event loop and it will alter what the plugin has to type.

~~**EDIT:** maybe I can try to figure it out, if it can be possible anyway, but in my spare time :rice_ball:~~
