### ISSUE TITLE
Typescript compatability

### ISSUE THREAD

**Issue by paulmck21** [codekraft-studio/angular-typed#3]
Hi There, this module looks great but my app is using Typescript and so is not compatible. Is there a possible fix for this?

Thanks

**Comment by codekraft-studio** [comment]
hi, sorry for the late response, I'm not using angular1 with typescript can you provide some error logs or a sample of your project setup (where are you using/importing angular-typed) so I can do some tests or fix specific errors?
Many thanks.

**Comment by b4dnewz** [comment]
closed due inactivity
