### ISSUE TITLE
Not working with 1.6.8

### ISSUE THREAD

**Issue by apmeena** [codekraft-studio/angular-typed#4]
I am trying to use the angular-typed module in my project. The working demo is running on angular version 1.5.8 but in my project, I am using 1.6.8. This is not working with 1.6.8. 

Thank you.

**Comment by b4dnewz** [comment]
Sorry man I misread the contents of the issue, I will try with angular 1.6.8, I assumed the CDN pointed to the last, which is not.. if you want you can post any specific warning or error that occurs.

**Comment by sarfarazansari** [comment]
@b4dnewz , @apmeena  tested and updated lib in demo page [https://github.com/codekraft-studio/angular-typed/pull/5](PR)
